# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc9582be06629c9e6cd7637372af724ef4008f2cbf3143f3473b0100d1cd0a41e2c11f9b67a5bf7945a69e04f4f832f48de8162bbe83272d7e1183673dd4166e

test:
  secret_key_base: 5ecd7eefbffe4dee9ca35bc54d6f22d72d4d50854662752dcbf00e7dfcbc0089eabed92f6d64f82449b5eb825068b95f2c2771fb27bd915cdfa6d2c9f6df2949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
